modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="pixelmonraid"
version="2.0"
displayName="Pixelmon Raid Mod"
authors="Dhanraj"
description='''
A custom Pixelmon raid system mod that spawns Raid boss Pok√©mon,
tracks player damage, splits rewards, and prevents boss from dying.
'''

[[dependencies.pixelmonraid]]
modId="forge"
mandatory=true
versionRange="[36.2.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.pixelmonraid]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5]"
ordering="NONE"
side="BOTH"

[[dependencies.pixelmonraid]]
modId="pixelmon"
mandatory=true
versionRange="[9.1.12,9.1.14]"
ordering="AFTER"
side="BOTH"